[global]
type=global
user_agent=VM-Lab-Asterisk

[transport-udp]
type=transport
protocol=udp
bind=10.85.30.30:5060

[1001]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=1001-auth
aors=1001
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=ChangeMe1001

[1001]
type=aor
max_contacts=1

[1002]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=1002-auth
aors=1002
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[1002-auth]
type=auth
auth_type=userpass
username=1002
password=ChangeMe1002

[1002]
type=aor
max_contacts=1

[1003]
type=endpoint
context=internal
disallow=all
allow=ulaw
auth=1003-auth
aors=1003
direct_media=no
force_rport=yes
rewrite_contact=yes
rtp_symmetric=yes

[1003-auth]
type=auth
auth_type=userpass
username=1003
password=ChangeMe1003

[1003]
type=aor
max_contacts=1
